name: ressc_profiler
description: "RESSC Trainee Directory and Profiles"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-134.1.beta <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0  #add dependency for auto size text
  transparent_image: ^2.0.1 #add transparent image for Fade-in Memory Image


  firebase_core: ^2.20.0  # add dependency for Firebase Core
  cloud_firestore: ^4.13.6  # add dependency for Cloud Firestore

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.12.0
  firebase_storage: ^11.5.1
  gif: ^2.3.0
  profile_picture: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    -  assets/media/