// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFYXqZIgtkF35VLuWdMVPZ-GE9J0ma49Y',
    appId: '1:158242454517:web:cc0e421f56a53246e67ebc',
    messagingSenderId: '158242454517',
    projectId: 'doh-chd-car-portal-app',
    authDomain: 'doh-chd-car-portal-app.firebaseapp.com',
    storageBucket: 'doh-chd-car-portal-app.appspot.com',
    measurementId: 'G-KF17H922K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQjjztJOS-vQlLWYQAHL0221Ezph3oPik',
    appId: '1:158242454517:android:6ec452e8e561873ae67ebc',
    messagingSenderId: '158242454517',
    projectId: 'doh-chd-car-portal-app',
    storageBucket: 'doh-chd-car-portal-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ksYe5i74XgY1IaPdd4_mZOI0HdZBQ64',
    appId: '1:158242454517:ios:f12b4ad6080c34f0e67ebc',
    messagingSenderId: '158242454517',
    projectId: 'doh-chd-car-portal-app',
    storageBucket: 'doh-chd-car-portal-app.appspot.com',
    iosBundleId: 'com.example.resscProfiler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8ksYe5i74XgY1IaPdd4_mZOI0HdZBQ64',
    appId: '1:158242454517:ios:3faf2304c5e404bbe67ebc',
    messagingSenderId: '158242454517',
    projectId: 'doh-chd-car-portal-app',
    storageBucket: 'doh-chd-car-portal-app.appspot.com',
    iosBundleId: 'com.example.resscProfiler.RunnerTests',
  );
}
